version: '3.8'
services:
  mysql_container:
    image: mysql:8
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nest_level1
    ports:
      - '3306:3306'
    volumes:
      - './my-sql.sql:/docker-entrypoint-initdb.d/1.sql'
